/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

/**
 *
 * @author patrick
 */
public class TelaLoginUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginUsuario
     */
    public TelaLoginUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldUserpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbUsuario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        txtFieldUsername.setMaximumSize(new java.awt.Dimension(400, 40));
        txtFieldUsername.setPreferredSize(new java.awt.Dimension(400, 38));
        getContentPane().add(txtFieldUsername);
        txtFieldUsername.setBounds(210, 310, 410, 38);

        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 280, 90, 18);

        txtFieldUserpassword.setMaximumSize(new java.awt.Dimension(400, 40));
        txtFieldUserpassword.setPreferredSize(new java.awt.Dimension(400, 38));
        getContentPane().add(txtFieldUserpassword);
        txtFieldUserpassword.setBounds(210, 400, 410, 38);

        jLabel3.setText("SENHA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 370, 90, 18);

        cbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretario", "Veterinario" }));
        getContentPane().add(cbUsuario);
        cbUsuario.setBounds(210, 230, 160, 38);

        jButton1.setBackground(new java.awt.Color(107, 79, 79));
        jButton1.setForeground(new java.awt.Color(251, 249, 249));
        jButton1.setText("ENTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 490, 410, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pet-clinica-logo-completa.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 60, 460, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-clinica-login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFieldUsername;
    private javax.swing.JTextField txtFieldUserpassword;
    // End of variables declaration//GEN-END:variables
}
